version: '2'
services:
  telegraf:
    image: appcelerator/telegraf:telegraf-1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    environment:
      OUTPUT_INFLUXDB_ENABLED: "true"
      INFLUXDB_URL: "http://influxdb:8086"
      INPUT_DOCKER_ENABLED: "true"
  influxdb:
    image: appcelerator/influxdb:influxdb-1.0
    environment:
      FORCE_HOSTNAME: auto
      CONFIG_ARCHIVE_URL: "https://github.com/appcelerator/amp-config/archive/0.3.0.tar.gz"
      PRE_CREATE_DB: "telegraf"
  kapacitor:
    image: appcelerator/kapacitor
    build: .
    environment:
      CONFIG_ARCHIVE_URL: "https://github.com/appcelerator/amp-config/archive/0.3.0.tar.gz"
      KAPACITOR_HOSTNAME: auto
      INFLUXDB_URL: http://influxdb:8086
      #SUBSCRIPTION_PROTOCOL: "udp"
  sut:
    image: appcelerator/sut
    build: ./sut
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - kapacitor
      - influxdb
      - telegraf
