version: '2'
services:
  consul:
    extends:
      file: docker-compose.yml
      service: consul
  influxdb:
    extends:
      file: docker-compose.yml
      service: influxdb
    depends_on:
      - consul
  kapacitor:
    extends:
      file: docker-compose.yml
      service: kapacitor
    depends_on:
      - influxdb
