version: '2'
services:
services:
  influxdb:
    image: appcelerator/influxdb:influxdb-1.0
    environment:
      FORCE_HOSTNAME: auto
      CONFIG_ARCHIVE_URL: "https://github.com/appcelerator/amp-config/archive/0.2.0.tar.gz"
      PRE_CREATE_DB: "telegraf"
    labels:
      - "ServiceUUId=system.influxdb"
  kapacitor:
    image: appcelerator/kapacitor
    build: .
    environment:
      CONFIG_ARCHIVE_URL: "https://github.com/appcelerator/amp-config/archive/0.2.0.tar.gz"
      KAPACITOR_HOSTNAME: auto
      INFLUXDB_URL: http://influxdb:8086
    depends_on:
      - influxdb
