version: '2'
services:
  influxdb:
    image: appcelerator/influxdb:latest
    environment:
      FORCE_HOSTNAME: auto
      CONFIG_ARCHIVE_URL: "https://github.com/appcelerator/amp-config/archive/0.1.0.tar.gz"
      PRE_CREATE_DB: "telegraf"
    labels:
      - "ServiceUUId=system.influxdb"
  kapacitor:
    image: appcelerator/kapacitor
    build: .
    environment:
      CONFIG_ARCHIVE_URL: "https://github.com/appcelerator/amp-config/archive/0.1.0.tar.gz"
      KAPACITOR_HOSTNAME: auto
      INFLUXDB_URL: http://influxdb:8086
  sut:
    image: appcelerator/sut
    build: ./sut
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - kapacitor
      - influxdb
    labels:
      - "io.appcelerator.amp.build.mounts=/var/run/docker.sock"
